version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: class_board_db
    environment:
      POSTGRES_DB: "CLASS-BOARD"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    container_name: class_board_web
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    restart: always

volumes:
  postgres_data:
