# Generated by Django 5.2.11 on 2026-03-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherabsence',
            name='end_date',
            field=models.DateField(db_index=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='teacherabsence',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='teachersubstitution',
            name='end_date',
            field=models.DateField(db_index=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='teachersubstitution',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='Start Date'),
        ),
    ]
